---
- name: Pull Image from Docker Hub
  hosts: all
  tasks:

    - name: Start docker service
      service:
        name: docker
        state: started
        
    - name: pull docker image
      shell: docker pull incogdark/scientific-calculator
      
    - name: running container
      shell: docker run -it -d incogdark/scientific-calculator